[package]
name = "geng-audio"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[dependencies]
batbox-la.workspace = true
batbox-num.workspace = true
batbox-time.workspace = true
anyhow.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { workspace = true, features = [
    "AudioContext",
    "AudioBuffer",
    "AudioBufferSourceNode",
    "AudioDestinationNode",
    "AudioParam",
    "AudioListener",
    "DistanceModelType",
    "PannerNode",
    "GainNode",
    "XmlHttpRequest",             # TODO should not be used
    "XmlHttpRequestResponseType", # TODO
] }
wasm-bindgen-futures.workspace = true
wasm-bindgen.workspace = true
js-sys.workspace = true
futures.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rodio.workspace = true
atomic_float.workspace = true
